name: Base-Infra

on:
  push:
    branches:
      - "MS-Demo-Base-Infra"

env:

jobs:
  AzureBicepDeploy:
    name: 'AzureBicepDeploy'
    runs-on: ubuntu-latest
 
    steps:
    -  name: Checkout Code
       uses: actions/checkout@v2

    -  name: Azure Login
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    -  name: Deploy template
       uses: azure/CLI@v1
       with:
         inlineScript: |
           az account show
           az deployment tenant create --template-file AzureCloud/MS-Demo/deployment.bicep --location eastus
   